name: leads-project

services:
  leads_frontend:
    container_name: leads_frontend
    build:
      context: ./leads-website
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
    depends_on:
      - leads_backend
  leads_backend:
    container_name: leads_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        PG_USER: ${PG_USER}
        PG_PASSWORD: ${PG_PASSWORD}
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres_db:5432/leads
      PG_USER: postgres
      PG_PASSWORD: postgres
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leads
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
